on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install mkosi
        run: sudo apt-get install mkosi -y
      - name: Build image
        run: sudo -E ./build.sh
        working-directory: ./mkosi
      - name: Archive image
        uses: actions/upload-artifact@v4
        with:
          name: mkosi-image
          path: ./mkosi/mkosi.output/lxd/lxd.tar.xz

      
  